<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_closeLargeModal</name>
   <tag></tag>
   <elementGuidId>9992f890-af75-4de2-ae00-e2741d957caa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closeLargeModal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'closeLargeModal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6704442b-5b00-4e33-b0b0-a88e6ecd2bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1f9f43cd-a129-4e6f-8457-ba4739b62fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closeLargeModal</value>
      <webElementGuid>317dd611-084b-4501-ad03-25ef9df7ccb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>bb4e18f8-5bef-4d12-bd63-a63c772a7d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>09f27232-fc50-40fb-be9f-384a3e14651a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-68d64ea972a04146ab3044afd93a17b2</value>
      <webElementGuid>0dd4f889-8006-4d05-b468-897644cf4945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'closeLargeModal']</value>
      <webElementGuid>1dd74b84-828c-4cc4-a2d4-b28bccd9bef3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'closeLargeModal']</value>
      <webElementGuid>32effff4-53da-4176-b1c5-7e468ddea325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'closeLargeModal' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>6e90c4be-d2db-49d6-8a3e-b32dd215a344</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
