<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_css-19bb58m_1</name>
   <tag></tag>
   <elementGuidId>34e5c5d2-69af-420d-88be-dd88791bc803</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#city [data-value=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'city']//*[@data-value = '']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>253c316b-fa9b-417b-ab62-0ac66de2496e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-19bb58m</value>
      <webElementGuid>255d5938-2166-4afb-9165-8ead36879299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4b59e5c1549f53083cfeb1bfa2e52276</value>
      <webElementGuid>886b55b9-2dc4-41c1-8c90-e687a9e97fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'city']//*[@data-value = '']</value>
      <webElementGuid>34581080-1597-4c94-bf8e-be01ef7b2f7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'city']//*[@data-value = '']</value>
      <webElementGuid>e5678b04-6f28-4d5f-b704-f10a575ec704</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
