<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_css-19bb58m</name>
   <tag></tag>
   <elementGuidId>1b5071c0-3eae-4b5a-8851-45ec2114fedb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#state [data-value=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'state']//*[@data-value = '']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5a14ffcc-07a8-42e2-858e-32d9a4e4178d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-19bb58m</value>
      <webElementGuid>d7b456a5-fcec-4155-b41f-c5373accf9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0cb8eac2dd90cb9612ca209195bc8a10</value>
      <webElementGuid>fe0ff705-8b38-4926-8af0-46a5dcfe814a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'state']//*[@data-value = '']</value>
      <webElementGuid>32788f70-6e00-4c23-8edd-da5e6f5f7211</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'state']//*[@data-value = '']</value>
      <webElementGuid>17437590-6973-4eab-841b-686625ffa628</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
